# src/rulebook/budget_owner.py
from __future__ import annotations
from typing import Tuple, List, Dict
import re

"""
budget_owner rulebook
---------------------
- Contract: infer(row) -> (value, rule_tag)
  * value:   resolved budget owner (str) or "" (blank) if unknown
  * rule_tag: provenance "budget_owner@<version>#<rule_id>" or "" if unknown

- Add/refresh patterns by regenerating from your candidate rules CSV and
  pasting them under _RULES (or import them from a generated module).
"""

RULEBOOK_NAME = "budget_owner"
RULEBOOK_VERSION = "2025.10.05"   # <-- bump when rules change
UNKNOWN = ""                      # blank fallback

# -----------------------------------------------------------------------------
# Patterns: list of (compiled_regex, resolved_owner, optional_rule_id_label)
# Optionally provide a human-friendly id; if omitted the ordinal index is used.
# -----------------------------------------------------------------------------
_RULES: List[Tuple[re.Pattern, str, str | None]] = [
    (re.compile(r'(?i)\bLABOR\b'), 'LINDA'),
    (re.compile(r'(?i)\bREVENUE\b'), ''),
    (re.compile(r'(?i)\bPAYNW\b'), 'LINDA'),
    (re.compile(r'(?i)\bCANNABIS\b'), ''),
    (re.compile(r'(?i)\bDIRECT\b'), 'LINDA'),
    (re.compile(r'(?i)\bGUSTO\b'), 'LINDA'),
    (re.compile(r'(?i)\bSWITCH\b'), ''),
    (re.compile(r'(?i)\bX0435\b'), ''),
    (re.compile(r'(?i)\bX0586\b'), ''),
    (re.compile(r'(?i)\bSETTLEMENT\b'), ''),
    (re.compile(r'(?i)\bEXECUTIVE\b'), 'JAY'),
    (re.compile(r'(?i)\bSTRONGHOLD\b'), ''),
    (re.compile(r'(?i)\bINVEST\b'), ''),
    (re.compile(r'(?i)\bTUV\b'), ''),
    (re.compile(r'(?i)\bSCHG\b'), ''),
    (re.compile(r'(?i)\bDEPOSITBRIDGEPLUS\b'), ''),
    (re.compile(r'(?i)\bTHANK\b'), ''),
    (re.compile(r'(?i)\bYOU\b'), ''),
    (re.compile(r'(?i)\bCHASE\b'), ''),
    (re.compile(r'(?i)\bCRD\b'), ''),
    (re.compile(r'(?i)\bFASTRAK\b'), 'ERIC'),
    (re.compile(r'(?i)\bSERIAL\b'), 'LINDA'),
    (re.compile(r'(?i)\bAPSMOAKLAND\b'), ''),
    (re.compile(r'(?i)\bSMOAKLANDSAC\b'), ''),
    (re.compile(r'(?i)\bDAILY\b'), ''),
    (re.compile(r'(?i)\bPAYM\b'), ''),
    (re.compile(r'(?i)\bTELEPHONE\b'), 'LINDA'),
    (re.compile(r'(?i)\bADOBE\b'), 'DOUG'),
    (re.compile(r'(?i)\bGREEN\b'), ''),
    (re.compile(r'(?i)\bLEDGER\b'), ''),
    (re.compile(r'(?i)\bARMOR\b'), 'CHANNA'),
    (re.compile(r'(?i)\bINTUIT\b'), 'DOUG'),
    (re.compile(r'(?i)\bQUICKBOOKS\b'), 'DOUG'),
    (re.compile(r'(?i)\bQBOOKS\b'), 'DOUG'),
    (re.compile(r'(?i)\bCASHLESS\b'), ''),
    (re.compile(r'(?i)\bMATRIX\b'), 'LINDA'),
    (re.compile(r'(?i)\bCINTAS\b'), 'DEREK'),
    (re.compile(r'(?i)\bDAILYPAYME\b'), ''),
    (re.compile(r'(?i)\bKLAVIYO\b'), 'DENNIS'),
    (re.compile(r'(?i)\bCOIN\b'), ''),
    (re.compile(r'(?i)\bCURRENCY\b'), ''),
    (re.compile(r'(?i)\bCOMCAST\b'), 'LINDA'),
    (re.compile(r'(?i)\bDOORDASH\b'), 'LINDA'),
    (re.compile(r'(?i)\bDINING\b'), 'LINDA'),
    (re.compile(r'(?i)\bKAISER\b'), 'LINDA'),
    (re.compile(r'(?i)\bBLAZE\b'), 'DOUG'),
    (re.compile(r'(?i)\bMONTHLY\b'), 'CHANNA'),
    (re.compile(r'(?i)\bGHOST\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPLIVO\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPLIVO\.COM\b'), 'DENNIS'),
    (re.compile(r'(?i)\bACTIVITY\b'), 'CHANNA'),
    (re.compile(r'(?i)\bANALYSIS\b'), 'CHANNA'),
    (re.compile(r'(?i)\bONL\b'), 'DOUG'),
    (re.compile(r'(?i)\bHUMAN\b'), 'LINDA'),
    (re.compile(r'(?i)\bX0000\b'), 'LINDA'),
    (re.compile(r'(?i)\bINS\b'), 'LINDA'),
    (re.compile(r'(?i)\bOTC\b'), ''),
    (re.compile(r'(?i)\bEMPYREAL\b'), 'CHANNA'),
    (re.compile(r'(?i)\bACC\b'), ''),
    (re.compile(r'(?i)\bAUTOMATIC\b'), ''),
    (re.compile(r'(?i)\bINDIVIDUAL\b'), ''),
    (re.compile(r'(?i)\bCARD\b'), ''),
    (re.compile(r'(?i)\bEMPYREALENTERPRI\b'), 'CHANNA'),
    (re.compile(r'(?i)\bBILLB\b'), 'DENNIS'),
    (re.compile(r'(?i)\bINTE\b'), 'LINDA'),
    (re.compile(r'(?i)\bA35810\b'), ''),
    (re.compile(r'(?i)\bDNS\b'), ''),
    (re.compile(r'(?i)\bLAW\b'), 'LINDA'),
    (re.compile(r'(?i)\bJOINTCOMMERCE\b'), 'DENNIS'),
    (re.compile(r'(?i)\bFCU\b'), ''),
    (re.compile(r'(?i)\bGAIN\b'), ''),
    (re.compile(r'(?i)\bTMOBILE\b'), 'LINDA'),
    (re.compile(r'(?i)\bLHI\b'), 'DENNIS'),
    (re.compile(r'(?i)\bCSC\b'), 'ERIC'),
    (re.compile(r'(?i)\bADS\b'), 'DENNIS'),
    (re.compile(r'(?i)\bSTOCK\b'), 'DOUG'),
    (re.compile(r'(?i)\bEPAYMENT\b'), ''),
    (re.compile(r'(?i)\bPARTN\b'), 'DENNIS'),
    (re.compile(r'(?i)\bVERCEL\b'), 'DOUG'),
    (re.compile(r'(?i)\bALIBABA\b'), 'DEREK'),
    (re.compile(r'(?i)\bMANDELA\b'), 'DEREK'),
    (re.compile(r'(?i)\bBUCKET\b'), 'LINDA'),
    (re.compile(r'(?i)\bHONEY\b'), 'LINDA'),
    (re.compile(r'(?i)\bWEINSTEIN\b'), 'LINDA'),
    (re.compile(r'(?i)\bCABBAGE\b'), 'DENNIS'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX8205\b'), 'LINDA'),
    (re.compile(r'(?i)\bAIRCALL\b'), 'DOUG'),
    (re.compile(r'(?i)\bGITHUB\b'), 'DOUG'),
    (re.compile(r'(?i)\bAMZN\.COM\b'), 'LINDA'),
    (re.compile(r'(?i)\bECHTRAI\b'), 'LINDA'),
    (re.compile(r'(?i)\bONFLEET\b'), 'ERIC'),
    (re.compile(r'(?i)\bAIRCALL\.IO\b'), 'DOUG'),
    (re.compile(r'(?i)\bHISIG\b'), 'LINDA'),
    (re.compile(r'(?i)\bHUMANA\b'), 'LINDA'),
    (re.compile(r'(?i)\bLLP\b'), 'LINDA'),
    (re.compile(r'(?i)\bATT\b'), 'LINDA'),
    (re.compile(r'(?i)\bBROWSERSTACK\b'), 'DOUG'),
    (re.compile(r'(?i)\bBROWSERSTACK\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bGSUITE\b'), 'DOUG'),
    (re.compile(r'(?i)\bMSFT\b'), 'DOUG'),
    (re.compile(r'(?i)\bCITI\b'), ''),
    (re.compile(r'(?i)\bPGANDE\b'), 'LINDA'),
    (re.compile(r'(?i)\bANALYTIC\b'), 'DENNIS'),
    (re.compile(r'(?i)\bCANVA\b'), 'DOUG'),
    (re.compile(r'(?i)\bATLAS\b'), 'LINDA'),
    (re.compile(r'(?i)\bCORPORATE\b'), 'LINDA'),
    (re.compile(r'(?i)\bMUNICIPAL\b'), 'LINDA'),
    (re.compile(r'(?i)\bDOUG\b'), 'DOUG'),
    (re.compile(r'(?i)\bNGO\b'), 'DOUG'),
    (re.compile(r'(?i)\bKONCAUSEWAY\b'), 'DEREK'),
    (re.compile(r'(?i)\bMOM\b'), ''),
    (re.compile(r'(?i)\bASTRA\b'), 'LINDA'),
    (re.compile(r'(?i)\bORIN\b'), 'ERIC'),
    (re.compile(r'(?i)\bCALLRAIL\b'), 'DOUG'),
    (re.compile(r'(?i)\bDNH\b'), 'DOUG'),
    (re.compile(r'(?i)\bEXCISE\b'), ''),
    (re.compile(r'(?i)\bFED\b'), ''),
    (re.compile(r'(?i)\bAPPFOLIO\b'), 'LINDA'),
    (re.compile(r'(?i)\bPCS\b'), 'LINDA'),
    (re.compile(r'(?i)\bADT\b'), 'DEREK'),
    (re.compile(r'(?i)\bHARBOR\b'), 'LINDA'),
    (re.compile(r'(?i)\bAUTOPY\b'), 'LINDA'),
    (re.compile(r'(?i)\bPREPD\b'), 'LINDA'),
    (re.compile(r'(?i)\bCREATIVE\b'), 'DOUG'),
    (re.compile(r'(?i)\bSAMSARA\b'), 'DOUG'),
    (re.compile(r'(?i)\bSPECTRUM\b'), 'DOUG'),
    (re.compile(r'(?i)\bFLOR\b'), ''),
    (re.compile(r'(?i)\bGRUPO\b'), ''),
    (re.compile(r'(?i)\bADS7475396058\b'), 'DENNIS'),
    (re.compile(r'(?i)\bWORLDWIDE\b'), 'CHANNA'),
    (re.compile(r'(?i)\bFEI\b'), 'LINDA'),
    (re.compile(r'(?i)\bMARCO\b'), 'LINDA'),
    (re.compile(r'(?i)\bACROPRO\b'), 'DOUG'),
    (re.compile(r'(?i)\bATLASSIAN\b'), 'DOUG'),
    (re.compile(r'(?i)\bCOMETCHAT\b'), 'DOUG'),
    (re.compile(r'(?i)\bSUBS\b'), 'DOUG'),
    (re.compile(r'(?i)\bTRELLO\b'), 'DOUG'),
    (re.compile(r'(?i)\bTRELLO\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bCHEVLEBEC\b'), 'WENDY'),
    (re.compile(r'(?i)\bCLOVER\b'), 'WENDY'),
    (re.compile(r'(?i)\bPASS\b'), ''),
    (re.compile(r'(?i)\bPASSNY\b'), ''),
    (re.compile(r'(?i)\bLC2400\b'), 'WENDY'),
    (re.compile(r'(?i)\bALKHEMIST\b'), ''),
    (re.compile(r'(?i)\bSMOAKLANDPORTH\b'), ''),
    (re.compile(r'(?i)\b08\.14\.2023\b'), 'LINDA'),
    (re.compile(r'(?i)\bPEREZ\b'), 'LINDA'),
    (re.compile(r'(?i)\bPMNT\b'), 'LINDA'),
    (re.compile(r'(?i)\bSTONEMARK\b'), 'LINDA'),
    (re.compile(r'(?i)\bALPINE\b'), 'DENNIS'),
    (re.compile(r'(?i)\bIOT\b'), 'ERIC'),
    (re.compile(r'(?i)\b07\.31\.2023\b'), 'LINDA'),
    (re.compile(r'(?i)\bACHTRANS\b'), 'LINDA'),
    (re.compile(r'(?i)\bWHSE\b'), 'LINDA'),
    (re.compile(r'(?i)\bXPRESSCPTL\b'), 'LINDA'),
    (re.compile(r'(?i)\bSQJERSEY\b'), 'JAY'),
    (re.compile(r'(?i)\bWTH\b'), 'CHANNA'),
    (re.compile(r'(?i)\bGODADDY\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bPRIMO\b'), 'DEREK'),
    (re.compile(r'(?i)\b08\.01\.2023\b'), 'LINDA'),
    (re.compile(r'(?i)\bLEGALZOOM\b'), 'LINDA'),
    (re.compile(r'(?i)\bMENDOZA\b'), 'LINDA'),
    (re.compile(r'(?i)\bBILLBOAR\b'), 'DENNIS'),
    (re.compile(r'(?i)\bSPARKS\b'), 'DENNIS'),
    (re.compile(r'(?i)\bZENITH\b'), 'DENNIS'),
    (re.compile(r'(?i)\bERACTOLL\b'), 'WENDY'),
    (re.compile(r'(?i)\bSTATIOOAKLAND\b'), 'WENDY'),
    (re.compile(r'(?i)\bCITYOFSAC_BIZTAXONLINE\b'), ''),
    (re.compile(r'(?i)\bDISPENSARY\b'), ''),
    (re.compile(r'(?i)\bSACR\b'), 'LINDA'),
    (re.compile(r'(?i)\bROOTS\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPEWESTLEY\b'), 'WENDY'),
    (re.compile(r'(?i)\bECOGREENINDUSTRIES\b'), 'DEREK'),
    (re.compile(r'(?i)\bECOGREENINDUSTRIES\.COM\b'), 'DEREK'),
    (re.compile(r'(?i)\bBRYANT\b'), ''),
    (re.compile(r'(?i)\bGILBE\b'), ''),
    (re.compile(r'(?i)\bSAC\.HDLGOV\b'), ''),
    (re.compile(r'(?i)\bSACRAMEN\b'), ''),
    (re.compile(r'(?i)\bHEADQUARTERS\b'), 'LINDA'),
    (re.compile(r'(?i)\bHONEYBUCKET\b'), 'LINDA'),
    (re.compile(r'(?i)\bSENTRY\b'), 'LINDA'),
    (re.compile(r'(?i)\bSTEPHANIE\b'), 'LINDA'),
    (re.compile(r'(?i)\bBILLBOARD\b'), 'DENNIS'),
    (re.compile(r'(?i)\bZOOM\b'), 'DOUG'),
    (re.compile(r'(?i)\bZOOM\.US\b'), 'DOUG'),
    (re.compile(r'(?i)\b079259SAN\b'), 'WENDY'),
    (re.compile(r'(?i)\bROOT\b'), 'DEREK'),
    (re.compile(r'(?i)\bSCIENCES\b'), 'DEREK'),
    (re.compile(r'(?i)\bAPP\b'), ''),
    (re.compile(r'(?i)\bBADUA\b'), ''),
    (re.compile(r'(?i)\bMARISA\b'), ''),
    (re.compile(r'(?i)\bBEGGS\b'), 'LINDA'),
    (re.compile(r'(?i)\bEDISON\b'), 'LINDA'),
    (re.compile(r'(?i)\bKING\b'), 'LINDA'),
    (re.compile(r'(?i)\bSECRETARY\b'), 'LINDA'),
    (re.compile(r'(?i)\bEVENT\b'), 'DENNIS'),
    (re.compile(r'(?i)\bDELIGHTED\b'), 'DOUG'),
    (re.compile(r'(?i)\bFRONT\b'), 'DOUG'),
    (re.compile(r'(?i)\bGODADDY\b'), 'DOUG'),
    (re.compile(r'(?i)\bUSA\b'), 'DEREK'),
    (re.compile(r'(?i)\b4ZN2A7PJMYQD\b'), ''),
    (re.compile(r'(?i)\bCONFIRMED\b'), ''),
    (re.compile(r'(?i)\bINVOICES\b'), ''),
    (re.compile(r'(?i)\bLOCATIONS\b'), ''),
    (re.compile(r'(?i)\bPICKUP\b'), ''),
    (re.compile(r'(?i)\bSCZZ\b'), ''),
    (re.compile(r'(?i)\bCOMM\b'), 'LINDA'),
    (re.compile(r'(?i)\bFRONTIER\b'), 'LINDA'),
    (re.compile(r'(?i)\bLIVE\b'), 'LINDA'),
    (re.compile(r'(?i)\bSCAN\b'), 'LINDA'),
    (re.compile(r'(?i)\bPAYMENTUS\b'), 'CHANNA'),
    (re.compile(r'(?i)\bPURCHASE09100001\b'), 'CHANNA'),
    (re.compile(r'(?i)\bBAKESFIELD\b'), 'WENDY'),
    (re.compile(r'(?i)\bHIGHLAND\b'), 'WENDY'),
    (re.compile(r'(?i)\bMUSKRAT\b'), ''),
    (re.compile(r'(?i)\bPACAFI\b'), ''),
    (re.compile(r'(?i)\bPCF\b'), ''),
    (re.compile(r'(?i)\bHUENEME\b'), 'LINDA'),
    (re.compile(r'(?i)\bADS3407900941\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPATIENT\b'), 'WENDY'),
    (re.compile(r'(?i)\bSTATIOORINDA\b'), 'WENDY'),
    (re.compile(r'(?i)\bFLAVORS\b'), 'DEREK'),
    (re.compile(r'(?i)\bCOMMISSION\b'), ''),
    (re.compile(r'(?i)\bRIVERSIDE\b'), ''),
    (re.compile(r'(?i)\bE\.T\.I\b'), 'LINDA'),
    (re.compile(r'(?i)\bMAITLANDM\b'), 'LINDA'),
    (re.compile(r'(?i)\bCELL\b'), 'CHANNA'),
    (re.compile(r'(?i)\bWIDE\b'), 'CHANNA'),
    (re.compile(r'(?i)\bRETAIL_PAY\b'), 'ERIC'),
    (re.compile(r'(?i)\b018\.00\b'), 'WENDY'),
    (re.compile(r'(?i)\bEXXONMOBIL\b'), 'WENDY'),
    (re.compile(r'(?i)\bCONES\b'), 'DEREK'),
    (re.compile(r'(?i)\bCUSTOM\b'), 'DEREK'),
    (re.compile(r'(?i)\bFILTRATION\b'), 'DEREK'),
    (re.compile(r'(?i)\bPRM\b'), 'DEREK'),
    (re.compile(r'(?i)\bUTILITY\b'), 'DEREK'),
    (re.compile(r'(?i)\bASHS\b'), ''),
    (re.compile(r'(?i)\bINDUS\b'), ''),
    (re.compile(r'(?i)\bREMOTE\b'), ''),
    (re.compile(r'(?i)\bSLO\b'), ''),
    (re.compile(r'(?i)\bDOPE\b'), 'DENNIS'),
    (re.compile(r'(?i)\bSPRINGBIG\b'), 'DENNIS'),
    (re.compile(r'(?i)\bAUTOMOT\b'), 'ERIC'),
    (re.compile(r'(?i)\bIMPORT\b'), 'ERIC'),
    (re.compile(r'(?i)\bTIRE\b'), 'ERIC'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX8630\b'), 'DOUG'),
    (re.compile(r'(?i)\bC043488NEWARK\b'), 'WENDY'),
    (re.compile(r'(?i)\bCHEVWESTLEY\b'), 'WENDY'),
    (re.compile(r'(?i)\bNETWOR\b'), 'DEREK'),
    (re.compile(r'(?i)\bANTIOCH\b'), ''),
    (re.compile(r'(?i)\bCENT\b'), ''),
    (re.compile(r'(?i)\bFHL\b'), ''),
    (re.compile(r'(?i)\bHEALING\b'), ''),
    (re.compile(r'(?i)\bKIM\b'), ''),
    (re.compile(r'(?i)\bTIGRANLEVONANDLA\b'), ''),
    (re.compile(r'(?i)\b08\.15\.2023\b'), 'LINDA'),
    (re.compile(r'(?i)\bFRANCHISE\b'), 'LINDA'),
    (re.compile(r'(?i)\bHIS2000444\b'), 'LINDA'),
    (re.compile(r'(?i)\bHIS2000461\b'), 'LINDA'),
    (re.compile(r'(?i)\bINS\.PMTS\b'), 'LINDA'),
    (re.compile(r'(?i)\bNET\b'), 'LINDA'),
    (re.compile(r'(?i)\bNEXT\b'), 'LINDA'),
    (re.compile(r'(?i)\bPREMIU\b'), 'LINDA'),
    (re.compile(r'(?i)\bREM\b'), 'LINDA'),
    (re.compile(r'(?i)\bWAVE\b'), 'LINDA'),
    (re.compile(r'(?i)\bMEDIAJEL\b'), 'DENNIS'),
    (re.compile(r'(?i)\bSEMRUSH\b'), 'DENNIS'),
    (re.compile(r'(?i)\bDROPBOX\b'), 'DOUG'),
    (re.compile(r'(?i)\bHOLDING\b'), ''),
    (re.compile(r'(?i)\bNORDHOFF\b'), ''),
    (re.compile(r'(?i)\bINS\.PREM\b'), 'LINDA'),
    (re.compile(r'(?i)\bPTB\b'), 'LINDA'),
    (re.compile(r'(?i)\bREADYREFRESH\b'), 'LINDA'),
    (re.compile(r'(?i)\bSYS\b'), 'LINDA'),
    (re.compile(r'(?i)\bWATERSERV\b'), 'LINDA'),
    (re.compile(r'(?i)\bONBOARD\b'), 'JAY'),
    (re.compile(r'(?i)\bCLTV8\b'), 'DENNIS'),
    (re.compile(r'(?i)\bDEMAND\b'), 'DENNIS'),
    (re.compile(r'(?i)\bSTEADY\b'), 'DENNIS'),
    (re.compile(r'(?i)\bCKO\b'), 'DOUG'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX7706\b'), 'DOUG'),
    (re.compile(r'(?i)\bAVISNYCFEE\b'), 'WENDY'),
    (re.compile(r'(?i)\bSINCLAIBUTTONWILLOW\b'), 'WENDY'),
    (re.compile(r'(?i)\bHEART\b'), ''),
    (re.compile(r'(?i)\bMANTECA\b'), ''),
    (re.compile(r'(?i)\bMONTEREY\b'), ''),
    (re.compile(r'(?i)\bPUREST\b'), ''),
    (re.compile(r'(?i)\bSINGLE\b'), ''),
    (re.compile(r'(?i)\bSMOKELAND\b'), ''),
    (re.compile(r'(?i)\bTECHNO\b'), ''),
    (re.compile(r'(?i)\bARIEL\b'), 'LINDA'),
    (re.compile(r'(?i)\bLICENSING\b'), 'LINDA'),
    (re.compile(r'(?i)\bMUNOZ\b'), 'LINDA'),
    (re.compile(r'(?i)\bYOUNG\b'), 'LINDA'),
    (re.compile(r'(?i)\bSENDGRID\b'), 'DENNIS'),
    (re.compile(r'(?i)\bROCKET\b'), 'ERIC'),
    (re.compile(r'(?i)\bACCELA\b'), 'DOUG'),
    (re.compile(r'(?i)\bKINDLE\b'), 'DOUG'),
    (re.compile(r'(?i)\bSHOPIFY\b'), 'DOUG'),
    (re.compile(r'(?i)\bUNLTD\b'), 'DOUG'),
    (re.compile(r'(?i)\bHILLS\b'), 'WENDY'),
    (re.compile(r'(?i)\bPASAN\b'), 'WENDY'),
    (re.compile(r'(?i)\bEARTHWISE\b'), 'DEREK'),
    (re.compile(r'(?i)\bWILTON\b'), 'DEREK'),
    (re.compile(r'(?i)\bARORA\b'), ''),
    (re.compile(r'(?i)\bBAKED\b'), ''),
    (re.compile(r'(?i)\bCORONA\b'), ''),
    (re.compile(r'(?i)\bDISPE\b'), ''),
    (re.compile(r'(?i)\bFRESHLY\b'), ''),
    (re.compile(r'(?i)\bINDIO\b'), ''),
    (re.compile(r'(?i)\bNSEW\b'), ''),
    (re.compile(r'(?i)\bNYC\b'), ''),
    (re.compile(r'(?i)\bPRIMPATCHARA\b'), ''),
    (re.compile(r'(?i)\bSENDER\b'), ''),
    (re.compile(r'(?i)\bTRADING\b'), ''),
    (re.compile(r'(?i)\b08\.07\.2023\b'), 'LINDA'),
    (re.compile(r'(?i)\bAARON\b'), 'LINDA'),
    (re.compile(r'(?i)\bCARLOS\b'), 'LINDA'),
    (re.compile(r'(?i)\bF54C43DBBDB1\b'), 'LINDA'),
    (re.compile(r'(?i)\bHIS2000442\b'), 'LINDA'),
    (re.compile(r'(?i)\bJPS\b'), 'LINDA'),
    (re.compile(r'(?i)\bMARTINEZ\b'), 'LINDA'),
    (re.compile(r'(?i)\bMELISSA\b'), 'LINDA'),
    (re.compile(r'(?i)\bOYAMASUSH\b'), 'LINDA'),
    (re.compile(r'(?i)\bPAYROLLSYS\b'), 'LINDA'),
    (re.compile(r'(?i)\bPERMANENTE\b'), 'LINDA'),
    (re.compile(r'(?i)\bSHAY\b'), 'LINDA'),
    (re.compile(r'(?i)\bXFINITY\b'), 'LINDA'),
    (re.compile(r'(?i)\bTST\b'), 'JAY'),
    (re.compile(r'(?i)\bANA\b'), 'DENNIS'),
    (re.compile(r'(?i)\bMARKETP\b'), 'CHANNA'),
    (re.compile(r'(?i)\bBLV\b'), 'ERIC'),
    (re.compile(r'(?i)\bFAX\b'), 'DOUG'),
    (re.compile(r'(?i)\bTIME\b'), 'DOUG'),
    (re.compile(r'(?i)\bYELLOWIMAGES\b'), 'DOUG'),
    (re.compile(r'(?i)\bYELLOWIMAGES\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bLTD\b'), 'WENDY'),
    (re.compile(r'(?i)\bSTATIOCASTAIC\b'), 'WENDY'),
    (re.compile(r'(?i)\bELHSBCHKHHHKH\b'), 'DEREK'),
    (re.compile(r'(?i)\bEVERON\b'), 'DEREK'),
    (re.compile(r'(?i)\bEXTRACTION\b'), 'DEREK'),
    (re.compile(r'(?i)\bFRAGRANCE\b'), 'DEREK'),
    (re.compile(r'(?i)\bMODERNIST\b'), 'DEREK'),
    (re.compile(r'(?i)\bMOLDS\b'), 'DEREK'),
    (re.compile(r'(?i)\bPANTRY\b'), 'DEREK'),
    (re.compile(r'(?i)\bPORTER\b'), 'DEREK'),
    (re.compile(r'(?i)\bPRECISION\b'), 'DEREK'),
    (re.compile(r'(?i)\b300\.00\b'), ''),
    (re.compile(r'(?i)\bANT\b'), ''),
    (re.compile(r'(?i)\bBANYAN\b'), ''),
    (re.compile(r'(?i)\bCHO\b'), ''),
    (re.compile(r'(?i)\bFLORA\b'), ''),
    (re.compile(r'(?i)\bFLORATERRA\b'), ''),
    (re.compile(r'(?i)\bGUARDIAN\b'), ''),
    (re.compile(r'(?i)\bSONOMA\b'), ''),
    (re.compile(r'(?i)\bWEHO\b'), ''),
    (re.compile(r'(?i)\bASSETS\b'), 'LINDA'),
    (re.compile(r'(?i)\bBARR\b'), 'LINDA'),
    (re.compile(r'(?i)\bDEREK\b'), 'LINDA'),
    (re.compile(r'(?i)\bFINANCING\b'), 'LINDA'),
    (re.compile(r'(?i)\bFIXED\b'), 'LINDA'),
    (re.compile(r'(?i)\bGILMOR\b'), 'LINDA'),
    (re.compile(r'(?i)\bGOMES\b'), 'LINDA'),
    (re.compile(r'(?i)\bHDN\b'), 'LINDA'),
    (re.compile(r'(?i)\bIMPROVEMENTS\b'), 'LINDA'),
    (re.compile(r'(?i)\bIRMA\b'), 'LINDA'),
    (re.compile(r'(?i)\bISLAMIC\b'), 'LINDA'),
    (re.compile(r'(?i)\bJATO\b'), 'LINDA'),
    (re.compile(r'(?i)\bLEASEHOLD\b'), 'LINDA'),
    (re.compile(r'(?i)\bLEONIDAS\b'), 'LINDA'),
    (re.compile(r'(?i)\bMICHAEL\b'), 'LINDA'),
    (re.compile(r'(?i)\bOBATA\b'), 'LINDA'),
    (re.compile(r'(?i)\bPFS\b'), 'LINDA'),
    (re.compile(r'(?i)\bPPD\b'), 'LINDA'),
    (re.compile(r'(?i)\bPROCESSING\b'), 'LINDA'),
    (re.compile(r'(?i)\bSAIGONHOU\b'), 'LINDA'),
    (re.compile(r'(?i)\bTARGET\.COM\b'), 'LINDA'),
    (re.compile(r'(?i)\bX0001\b'), 'LINDA'),
    (re.compile(r'(?i)\bX1182\b'), 'LINDA'),
    (re.compile(r'(?i)\bACDFEE\b'), 'CHANNA'),
    (re.compile(r'(?i)\bARMOREDCAR\b'), 'CHANNA'),
    (re.compile(r'(?i)\bMETRO\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPUBLISHING\b'), 'DENNIS'),
    (re.compile(r'(?i)\bTENSTRIKE\b'), 'DENNIS'),
    (re.compile(r'(?i)\bWPY\b'), 'DENNIS'),
    (re.compile(r'(?i)\bFOUR\b'), 'ERIC'),
    (re.compile(r'(?i)\bGROWTH\b'), 'DOUG'),
    (re.compile(r'(?i)\bMICROSOFT\b'), 'DOUG'),
    (re.compile(r'(?i)\bZIPPY\b'), 'ERIC'),
    (re.compile(r'(?i)\b00000WESTLEY\b'), 'WENDY'),
    (re.compile(r'(?i)\bARCBUTTONWILLOW\b'), 'WENDY'),
    (re.compile(r'(?i)\bCHEVBERKELEY\b'), 'WENDY'),
    (re.compile(r'(?i)\bCHEVORINDA\b'), 'WENDY'),
    (re.compile(r'(?i)\bFROOT\b'), 'WENDY'),
    (re.compile(r'(?i)\bSHENZHEN\b'), 'WENDY'),
    (re.compile(r'(?i)\bSUPER\b'), 'WENDY'),
    (re.compile(r'(?i)\bWEBSTAURANT\b'), 'DEREK'),
    (re.compile(r'(?i)\bARTESIA\b'), ''),
    (re.compile(r'(?i)\bBILLPAY\b'), ''),
    (re.compile(r'(?i)\bBILL_PAY\b'), ''),
    (re.compile(r'(?i)\bBLOOM\b'), ''),
    (re.compile(r'(?i)\bCALITA\b'), ''),
    (re.compile(r'(?i)\bDEPOSITS\b'), ''),
    (re.compile(r'(?i)\bEXIT\b'), ''),
    (re.compile(r'(?i)\bEXOTIC\b'), ''),
    (re.compile(r'(?i)\bEXTRACT\b'), ''),
    (re.compile(r'(?i)\bFINANCIALS\b'), ''),
    (re.compile(r'(?i)\bHILIFE\b'), ''),
    (re.compile(r'(?i)\bMAIL\b'), ''),
    (re.compile(r'(?i)\bMEGANS\b'), ''),
    (re.compile(r'(?i)\bNICE\b'), ''),
    (re.compile(r'(?i)\bNORTHBAY\b'), ''),
    (re.compile(r'(?i)\bNUCLEUS\b'), ''),
    (re.compile(r'(?i)\bPYMTS\b'), ''),
    (re.compile(r'(?i)\bSAEFONG\b'), ''),
    (re.compile(r'(?i)\bTHIRD\b'), ''),
    (re.compile(r'(?i)\bTWENTY8GRAMZ\b'), ''),
    (re.compile(r'(?i)\bWELLNES\b'), ''),
    (re.compile(r'(?i)\b3QHK\b'), 'LINDA'),
    (re.compile(r'(?i)\bBRIANA\b'), 'LINDA'),
    (re.compile(r'(?i)\bERIC\b'), 'LINDA'),
    (re.compile(r'(?i)\bEUNOIA\b'), 'LINDA'),
    (re.compile(r'(?i)\bFORMATION\b'), 'LINDA'),
    (re.compile(r'(?i)\bHONOR\b'), 'LINDA'),
    (re.compile(r'(?i)\bJAVEN\b'), 'LINDA'),
    (re.compile(r'(?i)\bJOHNSON\b'), 'LINDA'),
    (re.compile(r'(?i)\bKANDY\b'), 'LINDA'),
    (re.compile(r'(?i)\bLZC\b'), 'LINDA'),
    (re.compile(r'(?i)\bMARIA\b'), 'LINDA'),
    (re.compile(r'(?i)\bMORALES\b'), 'LINDA'),
    (re.compile(r'(?i)\bNYS\b'), 'LINDA'),
    (re.compile(r'(?i)\bPAYMENTS\b'), 'LINDA'),
    (re.compile(r'(?i)\bPIN\b'), 'LINDA'),
    (re.compile(r'(?i)\bRETA\b'), 'LINDA'),
    (re.compile(r'(?i)\bWINGSTOP\b'), 'LINDA'),
    (re.compile(r'(?i)\bYENI\b'), 'LINDA'),
    (re.compile(r'(?i)\bPAYROLL\b'), 'LINDA'),
    (re.compile(r'(?i)\bCOMMERCE\b'), ''),
    (re.compile(r'(?i)\bADMINISTRATION\b'), 'LINDA'),
    (re.compile(r'(?i)\bDEPARTMENT\b'), ''),
    (re.compile(r'(?i)\bINVESTMENTS\b'), ''),
    (re.compile(r'(?i)\bINTERCOMPANY\b'), ''),
    (re.compile(r'(?i)\bWHOLESALE\b'), 'WENDY'),
    (re.compile(r'(?i)\bB2B\b'), ''),
    (re.compile(r'(?i)\bUNIFORMS\b'), 'DEREK'),
    (re.compile(r'(?i)\bBNK\b'), ''),
    (re.compile(r'(?i)\bTOWN\b'), ''),
    (re.compile(r'(?i)\bOUTDOOR\b'), 'DENNIS'),
    (re.compile(r'(?i)\bADVERTISING\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPROMOTION\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPMTS\b'), 'LINDA'),
    (re.compile(r'(?i)\bTRUST\b'), 'LINDA'),
    (re.compile(r'(?i)\bEASTWEST\b'), 'CHANNA'),
    (re.compile(r'(?i)\bFACILITY\b'), 'LINDA'),
    (re.compile(r'(?i)\bHARRENS\b'), 'DEREK'),
    (re.compile(r'(?i)\bODOO\b'), ''),
    (re.compile(r'(?i)\bSUBLIM\b'), 'DEREK'),
    (re.compile(r'(?i)\bMARKETING\b'), 'DENNIS'),
    (re.compile(r'(?i)\bPETROL\b'), 'ERIC'),
    (re.compile(r'(?i)\bRECEIVED\b'), ''),
    (re.compile(r'(?i)\bFINANCE\b'), 'CHANNA'),
    (re.compile(r'(?i)\bCLOUD\b'), 'DOUG'),
    (re.compile(r'(?i)\bSALES\b'), ''),
    (re.compile(r'(?i)\bEPAY\b'), ''),
    (re.compile(r'(?i)\bDEPOSIT\b'), ''),
    (re.compile(r'(?i)\bTWILIO\b'), 'DENNIS'),
    (re.compile(r'(?i)\bKEYPOINT\b'), 'CHANNA'),
    (re.compile(r'(?i)\bTOTAL\b'), ''),
    (re.compile(r'(?i)\bOAK\b'), ''),
    (re.compile(r'(?i)\bDEPOSITED\b'), ''),
    (re.compile(r'(?i)\bWEST\b'), ''),
    (re.compile(r'(?i)\bAMEX\b'), ''),
    (re.compile(r'(?i)\bCASH\b'), ''),
    (re.compile(r'(?i)\bTECHNOLOGY\b'), 'DOUG'),
    (re.compile(r'(?i)\bMISC\b'), 'CHANNA'),
    (re.compile(r'(?i)\bDEPOS\b'), ''),
    (re.compile(r'(?i)\bGPS\b'), 'LINDA'),
    (re.compile(r'(?i)\bTELECHK\b'), 'LINDA'),
    (re.compile(r'(?i)\bAPPS\b'), 'DOUG'),
    (re.compile(r'(?i)\bHONG\b'), 'DEREK'),
    (re.compile(r'(?i)\bONE\b'), ''),
    (re.compile(r'(?i)\bFORMSWIFT\b'), 'DOUG'),
    (re.compile(r'(?i)\bFORMSWIFT\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bVALLEY\b'), 'WENDY'),
    (re.compile(r'(?i)\bMOMENTUM\b'), 'ERIC'),
    (re.compile(r'(?i)\bLABELS\b'), 'WENDY'),
    (re.compile(r'(?i)\bNORTH\b'), ''),
    (re.compile(r'(?i)\bMKTPLACE\b'), 'LINDA'),
    (re.compile(r'(?i)\bCAPITAL\b'), ''),
    (re.compile(r'(?i)\bREBILL\b'), ''),
    (re.compile(r'(?i)\bPROPERTY\b'), 'LINDA'),
    (re.compile(r'(?i)\bRDC\b'), ''),
    (re.compile(r'(?i)\bFLORALS\b'), 'WENDY'),
    (re.compile(r'(?i)\bELECTRICITY\b'), 'DEREK'),
    (re.compile(r'(?i)\bKUSHMEN\b'), 'WENDY'),
    (re.compile(r'(?i)\bLOCAL\b'), 'LINDA'),
    (re.compile(r'(?i)\bSPIRIT\b'), 'JAY'),
    (re.compile(r'(?i)\bDEEP\b'), 'DENNIS'),
    (re.compile(r'(?i)\bLONG\b'), 'WENDY'),
    (re.compile(r'(?i)\bFUNDING\b'), ''),
    (re.compile(r'(?i)\bCOMP\b'), 'LINDA'),
    (re.compile(r'(?i)\bAIRL\b'), 'JAY'),
    (re.compile(r'(?i)\bINBOUND\b'), ''),
    (re.compile(r'(?i)\bIBUDDY\b'), 'WENDY'),
    (re.compile(r'(?i)\bBACKGROUND\b'), 'LINDA'),
    (re.compile(r'(?i)\bOVERHEAD\b'), 'DEREK'),
    (re.compile(r'(?i)\bCHARGES\b'), 'CHANNA'),
    (re.compile(r'(?i)\bDEPT\b'), ''),
    (re.compile(r'(?i)\bEPMT\b'), ''),
    (re.compile(r'(?i)\bMEDIWASTE\b'), 'DEREK'),
    (re.compile(r'(?i)\bTAXES\b'), ''),
    (re.compile(r'(?i)\bJOINHOMEBASE\b'), 'DOUG'),
    (re.compile(r'(?i)\bJOINHOMEBASE\.COM\b'), 'DOUG'),
    (re.compile(r'(?i)\bAIRLINES\b'), 'JAY'),
    (re.compile(r'(?i)\bINTEREST\b'), 'LINDA'),
    (re.compile(r'(?i)\bBANK\b'), 'CHANNA'),
    (re.compile(r'(?i)\bMANUAL\b'), 'LINDA'),
    (re.compile(r'(?i)\bSMO\b'), 'LINDA'),
    (re.compile(r'(?i)\bBUSINESS\b'), 'LINDA'),
    (re.compile(r'(?i)\bWORLD\b'), 'CHANNA'),
    (re.compile(r'(?i)\bSPENCER\b'), 'LINDA'),
    (re.compile(r'(?i)\bUSE\b'), ''),
    (re.compile(r'(?i)\bCHECK\b'), 'LINDA'),
    (re.compile(r'(?i)\bMCGRIFF\b'), 'LINDA'),
    (re.compile(r'(?i)\bGSUITE_SMOAKLA\b'), 'DOUG'),
    (re.compile(r'(?i)\bCONSULTANTS\b'), 'CHANNA'),
    (re.compile(r'(?i)\bSIBANNA\b'), 'CHANNA'),
    (re.compile(r'(?i)\bTWITCHTVDON\b'), 'CHANNA'),
    (re.compile(r'(?i)\bAREA\b'), ''),
    (re.compile(r'(?i)\bPERMIT\b'), 'LINDA'),
    (re.compile(r'(?i)\bSOLUTIONS\b'), 'DOUG'),
    (re.compile(r'(?i)\bSTATION\b'), 'ERIC'),
    (re.compile(r'(?i)\bBEACH\b'), 'WENDY'),
    (re.compile(r'(?i)\bNELLA\b'), 'WENDY'),
    (re.compile(r'(?i)\b100\.00\b'), ''),
    (re.compile(r'(?i)\b800\.00\b'), ''),
    (re.compile(r'(?i)\bTARGET\b'), 'LINDA'),
]


# Which fields we concatenate to form the searchable text.
# Order matters; we include upstream resolutions to simplify patterns.
_SOURCE_COLS: List[str] = [
    "bank_account", "subentity", "bank_cc_num",
    "week_num",
    "description", "extended_description",
    "payee_vendor", 
    "cf_account",     
]

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def _normalize_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.upper().strip()
    return " ".join(s.split())

def _concat_row(row: Dict) -> str:
    parts: List[str] = []
    for c in _SOURCE_COLS:
        v = row.get(c, "")
        if v is None:
            v = ""
        parts.append(str(v))
    return _normalize_text(" | ".join([p for p in parts if p]))

def _rule_tag(i: int, custom: str | None) -> str:
    """
    Build a stable provenance tag:
      budget_owner@<version>#<id>
    where <id> is either an explicit label (custom) or the 1-based index.
    """
    rid = custom if (custom and custom.strip()) else str(i)
    return f"{RULEBOOK_NAME}@{RULEBOOK_VERSION}#{rid}"

# -----------------------------------------------------------------------------
# Public API
# -----------------------------------------------------------------------------
def infer(row: Dict) -> Tuple[str, str]:
    """
    Row-level API used by the universal resolver.
    Returns:
      (value, rule_tag) where value is the resolved budget_owner or "UNKNOWN".
      rule_tag is "budget_owner@<version>#<rule_id>" or "" if unknown.
    """
    text = _concat_row(row)
    if not text:
        return (UNKNOWN, "")

    for i, rule in enumerate(_RULES, start=1):
        # Accept (pattern, owner) or (pattern, owner, custom_id)
        if len(rule) == 3:
            pat, owner, custom_id = rule  # type: ignore[misc]
        else:
            pat, owner = rule            # type: ignore[misc]
            custom_id = None

        if pat.search(text):
            owner = (owner or "").strip()
            if owner:
                return (owner, _rule_tag(i, custom_id))
            # If rule maps to blank, treat as unknown (no tag)
            return (UNKNOWN, "")

    return (UNKNOWN, "")

def apply_rules_df(df) -> "pd.DataFrame":  # type: ignore
    """
    Vectorized convenience that produces 4 columns:
      budget_owner, budget_owner_rule_tag, budget_owner_confidence, budget_owner_source
    (Same semantics the universal resolver will add.)
    """
    import pandas as pd  # local import to keep this module light if pandas isn't needed

    values: List[str] = []
    tags: List[str] = []
    confs: List[float] = []
    srcs: List[str] = []

    for _, row in df.iterrows():
        v, tag = infer(row.to_dict())
        if v:
            values.append(v)
            tags.append(tag)
            confs.append(1.0)
            srcs.append("rule")
        else:
            values.append(UNKNOWN)
            tags.append("")
            confs.append(0.0)
            srcs.append("unknown")

    out = df.copy()
    out["budget_owner"] = values
    out["budget_owner_rule_tag"] = tags
    out["budget_owner_confidence"] = confs
    out["budget_owner_source"] = srcs
    return out
