"""
Auto-generated Payee/Vendor rules engine.
Strategy: Iterate deterministic regex rules (precision >= 0.90, coverage >= 5, ordered by precision then coverage).
"""

import re
import pandas as pd
from typing import List, Tuple

# --- Rules (pattern, payee, rule_id optional) --------------------------------
_RULES: List[Tuple[re.Pattern, str]] = [
    (re.compile(r'(?i)\bSWITCH\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bGUSTO\b'), 'GUSTO'),
    (re.compile(r'(?i)\bAEROPAY\b'), 'AEROPAY'),
    (re.compile(r'(?i)\bX0435\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bX0586\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bINVEST\b'), 'TUV INVESTMENTS'),
    (re.compile(r'(?i)\bTUV\b'), 'TUV INVESTMENTS'),
    (re.compile(r'(?i)\bSTRONGHOLD\b'), 'STRONGHOLD'),
    (re.compile(r'(?i)\bSCHG\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bDEPOSITBRIDGEPLUS\b'), 'ODOO B2B'),
    (re.compile(r'(?i)\bCHEVRON\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bAMZN\b'), 'AMAZON'),
    (re.compile(r'(?i)\bMKTP\b'), 'AMAZON'),
    (re.compile(r'(?i)\bSHELL\b'), 'SHELL'),
    (re.compile(r'(?i)\bAPSMOAKLAND\b'), 'AEROPAY'),
    (re.compile(r'(?i)\bSMOAKLANDSAC\b'), 'STRONGHOLD'),
    (re.compile(r'(?i)\bBELCOSTA\b'), 'BELCOSTA LABS'),
    (re.compile(r'(?i)\bARCO\b'), 'ARCO'),
    (re.compile(r'(?i)\bMKTPL\b'), 'AMAZON'),
    (re.compile(r'(?i)\bADOBE\b'), 'ADOBE'),
    (re.compile(r'(?i)\bLEDGER\b'), 'LEDGER GREEN'),
    (re.compile(r'(?i)\bOSS\b'), 'OSS'),
    (re.compile(r'(?i)\bARMORED\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bINTUIT\b'), 'QUICKBOOKS'),
    (re.compile(r'(?i)\bQBOOKS\b'), 'QUICKBOOKS'),
    (re.compile(r'(?i)\bMATRIX\b'), 'MATRIX TRUST'),
    (re.compile(r'(?i)\bCINTAS\b'), 'CINTAS CORP'),
    (re.compile(r'(?i)\bBNK\b'), 'WEST TOWN BNK'),
    (re.compile(r'(?i)\bTOWN\b'), 'WEST TOWN BNK'),
    (re.compile(r'(?i)\bDAILYPAYME\b'), 'WEST TOWN BNK'),
    (re.compile(r'(?i)\bKLAVIYO\b'), 'KLAVIYO'),
    (re.compile(r'(?i)\bSOUTHWES\b'), 'SOUTHWEST'),
    (re.compile(r'(?i)\bCOMCAST\b'), 'COMCAST'),
    (re.compile(r'(?i)\bEZPAY\b'), 'WASTE MGMT'),
    (re.compile(r'(?i)\bWASTE\b'), 'WASTE MGMT'),
    (re.compile(r'(?i)\bDUE\b'), 'KAISER'),
    (re.compile(r'(?i)\bKAISER\b'), 'KAISER'),
    (re.compile(r'(?i)\bAMAZON\.COM\b'), 'AMAZON'),
    (re.compile(r'(?i)\bBLAZE\b'), 'BLAZE'),
    (re.compile(r'(?i)\bGHOST\b'), 'GHOST MGMT'),
    (re.compile(r'(?i)\b83844WESTLEY\b'), 'ARCO'),
    (re.compile(r'(?i)\bPLIVO\.COM\b'), 'PLIVO'),
    (re.compile(r'(?i)\bHARRENS\b'), 'HARRENS LAB INC.'),
    (re.compile(r'(?i)\bSPEEDWAY\b'), 'SPEEDWAY'),
    (re.compile(r'(?i)\bACTIVITY\b'), 'EASTWEST BANK'),
    (re.compile(r'(?i)\bANALYSIS\b'), 'EASTWEST BANK'),
    (re.compile(r'(?i)\bAMPM\b'), 'ARCO'),
    (re.compile(r'(?i)\bONL\b'), 'QUICKBOOKS'),
    (re.compile(r'(?i)\bHUMAN\b'), 'HUMAN INTEREST'),
    (re.compile(r'(?i)\bX0000\b'), 'GUSTO'),
    (re.compile(r'(?i)\bJOINHOMEBASE\.COM\b'), 'JOINHOMEBASE'),
    (re.compile(r'(?i)\bPETROL\b'), 'ARCO'),
    (re.compile(r'(?i)\bSPIRIT\b'), 'SPIRIT AIRLINES'),
    (re.compile(r'(?i)\bWM\.COM\b'), 'WASTE MGMT'),
    (re.compile(r'(?i)\bINTELLIWORX\b'), 'INTELLIWORX PH'),
    (re.compile(r'(?i)\bEMPYREALENTERPRI\b'), 'EMPYREAL ENTERPRISES, LLC'),
    (re.compile(r'(?i)\bINTE\b'), 'HUMAN INTEREST'),
    (re.compile(r'(?i)\bCOSTCO\b'), 'COSTCO'),
    (re.compile(r'(?i)\bA35810\b'), 'DNS'),
    (re.compile(r'(?i)\bDNS\b'), 'DNS'),
    (re.compile(r'(?i)\bAIRL\b'), 'SPIRIT AIRLINES'),
    (re.compile(r'(?i)\bFRAZIE\b'), 'SPEEDWAY'),
    (re.compile(r'(?i)\bJOINTCOMMERCE\b'), 'JOINTCOMMERCE'),
    (re.compile(r'(?i)\bFCU\b'), 'GAIN FCU'),
    (re.compile(r'(?i)\bGAIN\b'), 'GAIN FCU'),
    (re.compile(r'(?i)\bACD\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bTMOBILE\b'), 'T-MOBILE'),
    (re.compile(r'(?i)\bLAZ\b'), 'LAZ PKG OAKLAND'),
    (re.compile(r'(?i)\bLHI\b'), 'LHI'),
    (re.compile(r'(?i)\bPKG\b'), 'LAZ PKG OAKLAND'),
    (re.compile(r'(?i)\bCSC\b'), 'FASTRAK'),
    (re.compile(r'(?i)\bFASTRAK\b'), 'FASTRAK'),
    (re.compile(r'(?i)\bSTOCK\b'), 'ADOBE'),
    (re.compile(r'(?i)\bEPAYMENT\b'), 'CC'),
    (re.compile(r'(?i)\bVERCEL\b'), 'VERCEL'),
    (re.compile(r'(?i)\bWEINSTEIN\b'), 'WEINSTEIN LOCAL'),
    (re.compile(r'(?i)\bCABBAGE\b'), 'HAPPY CABBAGE'),
    (re.compile(r'(?i)\bECHTRAI\b'), 'ECHTRAI LLC'),
    (re.compile(r'(?i)\bGITHUB\b'), 'GITHUB'),
    (re.compile(r'(?i)\bAMZN\.COM\b'), 'AMAZON'),
    (re.compile(r'(?i)\bHISIG\b'), 'HISIG'),
    (re.compile(r'(?i)\bONFLEET\b'), 'ONFLEET'),
    (re.compile(r'(?i)\bAIRCALL\.IO\b'), 'AIRCALL'),
    (re.compile(r'(?i)\bATT\b'), 'ATT'),
    (re.compile(r'(?i)\bBROWSERSTACK\.COM\b'), 'BROWSERSTACK'),
    (re.compile(r'(?i)\bMARKETPLACE\b'), 'GREENBAX MARKETPLACE'),
    (re.compile(r'(?i)\bMANDELA\b'), 'MANDELA PARTNERS LLC'),
    (re.compile(r'(?i)\bDISPOSAL\b'), 'MEDIWASTE DISPOSAL LLC'),
    (re.compile(r'(?i)\bMEDIWASTE\b'), 'MEDIWASTE DISPOSAL LLC'),
    (re.compile(r'(?i)\bPGANDE\b'), 'PG&E'),
    (re.compile(r'(?i)\bCITI\b'), 'CC'),
    (re.compile(r'(?i)\bADMIN\b'), 'PS ADMINISTRATORS'),
    (re.compile(r'(?i)\bATLAS\b'), 'ATLAS'),
    (re.compile(r'(?i)\bCANVA\b'), 'CANVA'),
    (re.compile(r'(?i)\bANALYTIC\b'), 'HAPPY CABBAGE'),
    (re.compile(r'(?i)\bCORPORATE\b'), 'GUSTO'),
    (re.compile(r'(?i)\bASTRA\b'), 'AD ASTRA LAW GROUP'),
    (re.compile(r'(?i)\bMUNICIPAL\b'), 'SACRAMENTO MUNICIPAL'),
    (re.compile(r'(?i)\bKONCAUSEWAY\b'), 'ALIBABA'),
    (re.compile(r'(?i)\bAPPFOLIO\b'), 'APPFOLIO, INC'),
    (re.compile(r'(?i)\bCALLRAIL\b'), 'CALLRAIL INC'),
    (re.compile(r'(?i)\bFORMSWIFT\.COM\b'), 'FORMSWIFT'),
    (re.compile(r'(?i)\bPCS\b'), 'T-MOBILE'),
    (re.compile(r'(?i)\bORIN\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bADT\b'), 'ADT'),
    (re.compile(r'(?i)\bDOUG\b'), 'DOUG NGO'),
    (re.compile(r'(?i)\bAUTOPY\b'), 'T-MOBILE'),
    (re.compile(r'(?i)\bPREPD\b'), 'T-MOBILE'),
    (re.compile(r'(?i)\bHOME\b'), 'THE HOME DEPOT'),
    (re.compile(r'(?i)\bLABELS\b'), 'ONLINE LABELS, INC.'),
    (re.compile(r'(?i)\bSAMSARA\b'), 'SAMSARA'),
    (re.compile(r'(?i)\bSHIP\b'), 'ULINE'),
    (re.compile(r'(?i)\bSPECTRUM\b'), 'SPECTRUM'),
    (re.compile(r'(?i)\bULINE\b'), 'ULINE'),
    (re.compile(r'(?i)\bCREATIVE\b'), 'ADOBE'),
    (re.compile(r'(?i)\bATM\b'), 'WORLDWIDE ATM'),
    (re.compile(r'(?i)\bCHEFSTORE\b'), 'CHEFSTORE'),
    (re.compile(r'(?i)\bADS7475396058\b'), 'GOOGLE ADS'),
    (re.compile(r'(?i)\bACCOUNTFEE\b'), 'NBCU'),
    (re.compile(r'(?i)\bMKTPLACE\b'), 'AMAZON'),
    (re.compile(r'(?i)\bATLASSIAN\b'), 'TRELLO'),
    (re.compile(r'(?i)\bCOMETCHAT\b'), 'COMETCHAT'),
    (re.compile(r'(?i)\bPASSNY\b'), 'E-Z*PASS'),
    (re.compile(r'(?i)\bTRELLO\.COM\b'), 'TRELLO'),
    (re.compile(r'(?i)\bFEI\b'), 'MARCO FEI'),
    (re.compile(r'(?i)\bMARCO\b'), 'MARCO FEI'),
    (re.compile(r'(?i)\bACROPRO\b'), 'ADOBE'),
    (re.compile(r'(?i)\bSUBS\b'), 'ADOBE'),
    (re.compile(r'(?i)\bCHEVLEBEC\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bFLORALS\b'), 'FAMILY FLORALS'),
    (re.compile(r'(?i)\bPMNT\b'), 'STONEMARK'),
    (re.compile(r'(?i)\bBUD\b'), 'BUD TECHNOLOGY'),
    (re.compile(r'(?i)\bSMOAKLANDPORTH\b'), 'STRONGHOLD'),
    (re.compile(r'(?i)\bALPINE\b'), 'ALPINE IQ'),
    (re.compile(r'(?i)\bIOT\b'), 'MOMENTUM IOT'),
    (re.compile(r'(?i)\bXEVEN\b'), 'XEVEN SOLUTIONS'),
    (re.compile(r'(?i)\bPARKINGCENTRA\b'), 'PARKINGCENTRAL'),
    (re.compile(r'(?i)\bNGO\b'), 'DOUG NGO'),
    (re.compile(r'(?i)\bACHTRANS\b'), 'ATLAS'),
    (re.compile(r'(?i)\bXPRESSCPTL\b'), 'ATLAS'),
    (re.compile(r'(?i)\bBUCKET\b'), 'HONEY BUCKET'),
    (re.compile(r'(?i)\bHONEY\b'), 'HONEY BUCKET'),
    (re.compile(r'(?i)\bWHSE\b'), 'COSTCO'),
    (re.compile(r'(?i)\bPRIMO\b'), 'PRIMO WATER'),
    (re.compile(r'(?i)\bSQJERSEY\b'), 'MORGAN AT PROVOST'),
    (re.compile(r'(?i)\bSPAGHETTI\b'), 'SPAGHETTI NETWORK INC'),
    (re.compile(r'(?i)\bREMITCTR\b'), 'EBMUD'),
    (re.compile(r'(?i)\bWTH\b'), 'OSS'),
    (re.compile(r'(?i)\bSPARKS\b'), 'SPARKS MARKETING'),
    (re.compile(r'(?i)\bHEGENBERGER\b'), 'HEGENBERGER'),
    (re.compile(r'(?i)\bAVIS\b'), 'AVIS RENT-A-CAR'),
    (re.compile(r'(?i)\bCITYOFSAC_BIZTAXONLINE\b'), 'CITY OF SACRAMENTO'),
    (re.compile(r'(?i)\bBILLBOAR\b'), 'MESA'),
    (re.compile(r'(?i)\bSTATIOOAKLAND\b'), 'SHELL'),
    (re.compile(r'(?i)\bBRYANT\b'), 'BRYANT AND GILBE'),
    (re.compile(r'(?i)\bECOGREENINDUSTRIES\.COM\b'), 'ECOGREENINDUSTRIES'),
    (re.compile(r'(?i)\bGILBE\b'), 'BRYANT AND GILBE'),
    (re.compile(r'(?i)\bHOLIDAY\b'), 'HOLIDAY INN'),
    (re.compile(r'(?i)\bROOTS\b'), 'DEEP ROOTS'),
    (re.compile(r'(?i)\bSENTRY\b'), 'SENTRY'),
    (re.compile(r'(?i)\bHONEYBUCKET\b'), 'HONEY BUCKET'),
    (re.compile(r'(?i)\bSAC\.HDLGOV\b'), 'CITY OF SACRAMENTO'),
    (re.compile(r'(?i)\bSACRAMEN\b'), 'CITY OF SACRAMENTO'),
    (re.compile(r'(?i)\bPEWESTLEY\b'), 'ARCO'),
    (re.compile(r'(?i)\bIBUDDY\b'), 'IBUDDY INC'),
    (re.compile(r'(?i)\bKING\b'), 'SECURITY MARKETING KING'),
    (re.compile(r'(?i)\bSECRETARY\b'), 'CA SECRETARY OF STATE'),
    (re.compile(r'(?i)\bTOYOTA\b'), 'TOYOTA FINANCIAL'),
    (re.compile(r'(?i)\bZOOM\.US\b'), 'ZOOM'),
    (re.compile(r'(?i)\b079259SAN\b'), 'ENTERPRISE RENT-A-CAR'),
    (re.compile(r'(?i)\bDELIGHTED\b'), 'DELIGHTED, LLC'),
    (re.compile(r'(?i)\bFARMS\b'), 'PATCHWORK FARMS'),
    (re.compile(r'(?i)\bFRONTIER\b'), 'FRONTIER COMM CORP WEB'),
    (re.compile(r'(?i)\bLIVE\b'), 'CAPITAL LIVE SCAN'),
    (re.compile(r'(?i)\bMETERS\b'), 'NYCDOT PARKING METERS'),
    (re.compile(r'(?i)\bNYCDOT\b'), 'NYCDOT PARKING METERS'),
    (re.compile(r'(?i)\bPATCHWORK\b'), 'PATCHWORK FARMS'),
    (re.compile(r'(?i)\bSCAN\b'), 'CAPITAL LIVE SCAN'),
    (re.compile(r'(?i)\bSCZZ\b'), 'SCZZ COLLECTIVE'),
    (re.compile(r'(?i)\bEDISON\b'), 'EDISON'),
    (re.compile(r'(?i)\bSTONEMARK\b'), 'STONEMARK'),
    (re.compile(r'(?i)\bAUTOPAY\b'), 'MRKSCHNDRMNINSRN'),
    (re.compile(r'(?i)\bMRKSCHNDRMNINSRN\b'), 'MRKSCHNDRMNINSRN'),
    (re.compile(r'(?i)\bCONFIRMED\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bPICKUP\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bELITESECURI\b'), 'ELITESECURITY'),
    (re.compile(r'(?i)\bHAUL\b'), 'U-HAUL'),
    (re.compile(r'(?i)\bMUSKRAT\b'), 'CIRCLE MUSKRAT'),
    (re.compile(r'(?i)\bPAL\b'), 'OLD PAL LLC'),
    (re.compile(r'(?i)\bPAYMENTUS\b'), 'US CORPORATION'),
    (re.compile(r'(?i)\bCOMM\b'), 'FRONTIER COMM CORP WEB'),
    (re.compile(r'(?i)\bLOCATIONS\b'), 'SUMMIT LOCATIONS TRANSFER 240104 4ZN2A7PJMYQD'),
    (re.compile(r'(?i)\bLEGALZOOM\b'), 'LEGALZOOM'),
    (re.compile(r'(?i)\bPURCHASE09100001\b'), 'EMPYREAL ENTERPRISES, LLC'),
    (re.compile(r'(?i)\bE\.T\.I\b'), 'E.T.I. FINANCIAL'),
    (re.compile(r'(?i)\bGRAINGER\b'), 'GRAINGER'),
    (re.compile(r'(?i)\bBAKESFIELD\b'), 'KUSHMEN & BAKESFIELD ENTERPRISES'),
    (re.compile(r'(?i)\bOLD\b'), 'OLD PAL LLC'),
    (re.compile(r'(?i)\bGODADDY\.COM\b'), 'GODADDY.COM'),
    (re.compile(r'(?i)\bADS3407900941\b'), 'GOOGLE ADS'),
    (re.compile(r'(?i)\bMAITLANDM\b'), 'DOORDASH'),
    (re.compile(r'(?i)\bGREENBAXMRB\b'), 'NBCU'),
    (re.compile(r'(?i)\bCOMMISSION\b'), 'LEDGER GREEN'),
    (re.compile(r'(?i)\bSTATIOORINDA\b'), 'SHELL'),
    (re.compile(r'(?i)\bCONES\b'), 'CUSTOM CONES USA'),
    (re.compile(r'(?i)\bCUSTOM\b'), 'CUSTOM CONES USA'),
    (re.compile(r'(?i)\bFILTRATION\b'), 'SP PRM FILTRATION'),
    (re.compile(r'(?i)\bPRM\b'), 'SP PRM FILTRATION'),
    (re.compile(r'(?i)\bSIBANNA\b'), 'SIBANNA CONSULTANTS'),
    (re.compile(r'(?i)\bTWITCHTVDON\b'), 'TWITCHTVDON'),
    (re.compile(r'(?i)\bRETAIL_PAY\b'), 'TOYOTA FINANCIAL'),
    (re.compile(r'(?i)\bROOT\b'), 'ROOT SCIENCES'),
    (re.compile(r'(?i)\bCELL\b'), 'WORLDWIDE ATM'),
    (re.compile(r'(?i)\bWIDE\b'), 'WORLDWIDE ATM'),
    (re.compile(r'(?i)\bWORLDWIDE\b'), 'WORLDWIDE ATM'),
    (re.compile(r'(?i)\bEXXONMOBIL\b'), 'EXXON'),
    (re.compile(r'(?i)\bAUTOMOT\b'), 'ALAMEDA IMPORT'),
    (re.compile(r'(?i)\bDOPE\b'), 'DOPE MARKETING'),
    (re.compile(r'(?i)\bIMPORT\b'), 'ALAMEDA IMPORT'),
    (re.compile(r'(?i)\bINS\.PMTS\b'), 'NEXT WAVE'),
    (re.compile(r'(?i)\bKIM\b'), 'KIM INVESTMENTS'),
    (re.compile(r'(?i)\bNEXT\b'), 'NEXT WAVE'),
    (re.compile(r'(?i)\bPREMIU\b'), 'NEXT WAVE'),
    (re.compile(r'(?i)\bROBBIE\b'), 'ROTTEN ROBBIE'),
    (re.compile(r'(?i)\bSPRINGBIG\b'), 'SPRINGBIG'),
    (re.compile(r'(?i)\bTIGRANLEVONANDLA\b'), 'TIGRANLEVONANDLA'),
    (re.compile(r'(?i)\bWAVE\b'), 'NEXT WAVE'),
    (re.compile(r'(?i)\bPILOT\b'), 'PILOT'),
    (re.compile(r'(?i)\bSCIENCES\b'), 'ROOT SCIENCES'),
    (re.compile(r'(?i)\bNETWOR\b'), 'SPAGHETTI NETWORK INC'),
    (re.compile(r'(?i)\bHIS2000444\b'), 'HISIG'),
    (re.compile(r'(?i)\bHIS2000461\b'), 'HISIG'),
    (re.compile(r'(?i)\bEMPYREAL\b'), 'EMPYREAL ENTERPRISES, LLC'),
    (re.compile(r'(?i)\bC043488NEWARK\b'), 'ALAMO RENT-A-CAR'),
    (re.compile(r'(?i)\bGREENBAXDEBITCAR\b'), 'NBCU'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX8630\b'), 'ADOBE'),
    (re.compile(r'(?i)\bCHEVWESTLEY\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bNET\b'), 'GUSTO'),
    (re.compile(r'(?i)\bREM\b'), 'GUSTO'),
    (re.compile(r'(?i)\b08\.15\.2023\b'), 'PAYNW'),
    (re.compile(r'(?i)\bDROPBOX\b'), 'DROPBOX'),
    (re.compile(r'(?i)\bMEDIAJEL\b'), 'MEDIAJEL'),
    (re.compile(r'(?i)\bNORDHOFF\b'), 'THE NORDHOFF COM'),
    (re.compile(r'(?i)\bREADYREFRESH\b'), 'READYREFRESH'),
    (re.compile(r'(?i)\bSEMRUSH\b'), 'SEMRUSH'),
    (re.compile(r'(?i)\bVISTAPRINT\b'), 'VISTAPRINT'),
    (re.compile(r'(?i)\bWATERSERV\b'), 'READYREFRESH'),
    (re.compile(r'(?i)\bKAT\b'), 'INFINITY'),
    (re.compile(r'(?i)\bOPSMO\b'), 'OLD PAL LLC'),
    (re.compile(r'(?i)\bGENERAL\b'), 'ATLAS'),
    (re.compile(r'(?i)\bINS\.PREM\b'), 'ATLAS'),
    (re.compile(r'(?i)\bPTB\b'), 'PAYNW'),
    (re.compile(r'(?i)\bSYS\b'), 'PAYNW'),
    (re.compile(r'(?i)\bADCHEM\b'), 'ADCHEM LLC'),
    (re.compile(r'(?i)\bCANOPY\b'), 'CANOPY JERSEY CITY'),
    (re.compile(r'(?i)\bDEMAND\b'), 'STEADY DEMAND'),
    (re.compile(r'(?i)\bJERSEY\b'), 'CANOPY JERSEY CITY'),
    (re.compile(r'(?i)\bMANTECA\b'), 'MANTECA LLC'),
    (re.compile(r'(?i)\bMONTEREY\b'), 'MONTEREY LLC'),
    (re.compile(r'(?i)\bSTEADY\b'), 'STEADY DEMAND'),
    (re.compile(r'(?i)\bYOUNG\b'), 'SPENCER YOUNG LAW PC'),
    (re.compile(r'(?i)\bAVISNYCFEE\b'), 'AVIS FEE'),
    (re.compile(r'(?i)\bCHANGER\b'), 'OIL CHANGER HQ'),
    (re.compile(r'(?i)\bINSURAN\b'), 'MRKSCHNDRMNINSRN'),
    (re.compile(r'(?i)\bSCHNEIDERMAN\b'), 'MRKSCHNDRMNINSRN'),
    (re.compile(r'(?i)\bAVIS\.COM\b'), 'AVIS RENT-A-CAR'),
    (re.compile(r'(?i)\bPREPAY\b'), 'AVIS RENT-A-CAR'),
    (re.compile(r'(?i)\bGSUITE\b'), 'GOOGLE GSUITE'),
    (re.compile(r'(?i)\bCKO\b'), 'AIRCALL'),
    (re.compile(r'(?i)\bONBOARD\b'), 'SPIRIT AIRLINES'),
    (re.compile(r'(?i)\bBOARDING\b'), 'UNITED'),
    (re.compile(r'(?i)\bUPGRADED\b'), 'UNITED'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX7706\b'), 'ADOBE'),
    (re.compile(r'(?i)\bARIEL\b'), 'GUSTO'),
    (re.compile(r'(?i)\bACCELA\b'), 'ACCELA WEB'),
    (re.compile(r'(?i)\bARORA\b'), 'PRIMPATCHARA ARORA'),
    (re.compile(r'(?i)\bEARTHWISE\b'), 'EARTHWISE PACKAGING'),
    (re.compile(r'(?i)\bINDIO\b'), 'OTC INDIO LLC'),
    (re.compile(r'(?i)\bJPS\b'), 'JPS INC.'),
    (re.compile(r'(?i)\bKINDLE\b'), 'KINDLE UNLTD'),
    (re.compile(r'(?i)\bPRIMPATCHARA\b'), 'PRIMPATCHARA ARORA'),
    (re.compile(r'(?i)\bSHOPIFY\b'), 'SHOPIFY'),
    (re.compile(r'(?i)\bUNLTD\b'), 'KINDLE UNLTD'),
    (re.compile(r'(?i)\bWILTON\b'), 'WILTON'),
    (re.compile(r'(?i)\bCOPY\b'), 'STAR COPY'),
    (re.compile(r'(?i)\bRES\b'), 'LAFAYETTE RES METER PARK'),
    (re.compile(r'(?i)\bDISPE\b'), 'HAPPY DAYS DISPENSARY INC'),
    (re.compile(r'(?i)\bALKHEMIST\b'), 'ALKHEMIST DM LLC'),
    (re.compile(r'(?i)\bPASAN\b'), 'PARKINGCENTRAL'),
    (re.compile(r'(?i)\bHIS2000442\b'), 'HISIG'),
    (re.compile(r'(?i)\bSENDGRID\b'), 'TWILIO'),
    (re.compile(r'(?i)\bOYAMASUSH\b'), 'DOORDASH'),
    (re.compile(r'(?i)\bPERMANENTE\b'), 'KAISER'),
    (re.compile(r'(?i)\bXFINITY\b'), 'COMCAST'),
    (re.compile(r'(?i)\bF54C43DBBDB1\b'), 'GUSTO'),
    (re.compile(r'(?i)\bMELISSA\b'), 'GUSTO'),
    (re.compile(r'(?i)\bPAYROLLSYS\b'), 'PAYNW'),
    (re.compile(r'(?i)\bBAKEFIELDS\b'), 'KUSHMEN & BAKEFIELDS'),
    (re.compile(r'(?i)\bBANYAN\b'), 'BANYAN TREE'),
    (re.compile(r'(?i)\bBLV\b'), 'MT DIABLO'),
    (re.compile(r'(?i)\bBONDS\b'), 'ZIP BONDS'),
    (re.compile(r'(?i)\bCHO\b'), 'SONOMA CHO LLC'),
    (re.compile(r'(?i)\bELHSBCHKHHHKH\b'), 'HONGKONG PORTER'),
    (re.compile(r'(?i)\bEVERON\b'), 'EVERON LLC'),
    (re.compile(r'(?i)\bEXTRACTION\b'), 'CALIFORNIA EXTRACTION'),
    (re.compile(r'(?i)\bFLORA\b'), 'SONOMA CHO LLC'),
    (re.compile(r'(?i)\bFLORATERRA\b'), 'SONOMA CHO LLC'),
    (re.compile(r'(?i)\bGILMOR\b'), 'SHAY AARON GILMOR'),
    (re.compile(r'(?i)\bHDN\b'), 'SHAY AARON GILMOR'),
    (re.compile(r'(?i)\bPORTER\b'), 'HONGKONG PORTER'),
    (re.compile(r'(?i)\bSONOMA\b'), 'SONOMA CHO LLC'),
    (re.compile(r'(?i)\bUPRINTING\b'), 'UPRINTING'),
    (re.compile(r'(?i)\bYELLOWIMAGES\.COM\b'), 'YELLOWIMAGES'),
    (re.compile(r'(?i)\bZIP\b'), 'ZIP BONDS'),
    (re.compile(r'(?i)\bHEART\b'), 'THE PUREST HEART 786 INC'),
    (re.compile(r'(?i)\bPUREST\b'), 'THE PUREST HEART 786 INC'),
    (re.compile(r'(?i)\bFAX\b'), 'DROPBOX'),
    (re.compile(r'(?i)\bTIME\b'), 'DROPBOX'),
    (re.compile(r'(?i)\bTARGET\.COM\b'), 'TARGET'),
    (re.compile(r'(?i)\bCONSULTANT\b'), 'SIBANNA CONSULTANTS'),
    (re.compile(r'(?i)\bX1182\b'), 'E.T.I. FINANCIAL'),
    (re.compile(r'(?i)\bFEDEX\b'), 'FEDEX'),
    (re.compile(r'(?i)\bFINANCING\b'), 'STONEMARK'),
    (re.compile(r'(?i)\bPFS\b'), 'STONEMARK'),
    (re.compile(r'(?i)\bANA\b'), 'HAPPY CABBAGE'),
    (re.compile(r'(?i)\bSAIGONHOU\b'), 'DOORDASH'),
    (re.compile(r'(?i)\bPPD\b'), 'KAISER'),
    (re.compile(r'(?i)\b83232RCH\b'), 'ARCO'),
    (re.compile(r'(?i)\bSTATIOCASTAIC\b'), 'SHELL'),
    (re.compile(r'(?i)\bDEREK\b'), 'GUSTO'),
    (re.compile(r'(?i)\bOBATA\b'), 'GUSTO'),
    (re.compile(r'(?i)\bX0001\b'), 'GUSTO'),
    (re.compile(r'(?i)\bBARR\b'), 'PAYNW'),
    (re.compile(r'(?i)\bGOMES\b'), 'PAYNW'),
    (re.compile(r'(?i)\bIRMA\b'), 'PAYNW'),
    (re.compile(r'(?i)\bLEONIDAS\b'), 'PAYNW'),
    (re.compile(r'(?i)\bMICHAEL\b'), 'PAYNW'),
    (re.compile(r'(?i)\bACME\b'), 'ACME FIRE EXTINGUISHER CO'),
    (re.compile(r'(?i)\bBILL_PAY\b'), 'TWENTY8GRAMZ'),
    (re.compile(r'(?i)\bCALITA\b'), 'CALITA INC.'),
    (re.compile(r'(?i)\bEUNOIA\b'), 'EUNOIA CONSULTING GROUP LLC'),
    (re.compile(r'(?i)\bEXTINGUISHER\b'), 'ACME FIRE EXTINGUISHER CO'),
    (re.compile(r'(?i)\bFARMER\b'), "FARMER'S FRIDGE"),
    (re.compile(r'(?i)\bFRIDGE\b'), "FARMER'S FRIDGE"),
    (re.compile(r'(?i)\bGROWTH\b'), 'FRONT GROWTH'),
    (re.compile(r'(?i)\bHILIFE\b'), 'HILIFE GROUP'),
    (re.compile(r'(?i)\bHONOR\b'), 'HONOR'),
    (re.compile(r'(?i)\bMETRO\b'), 'METRO PUBLISHING'),
    (re.compile(r'(?i)\bPAYMENTS\b'), 'FRANCHISE TAX'),
    (re.compile(r'(?i)\bPUBLISHING\b'), 'METRO PUBLISHING'),
    (re.compile(r'(?i)\bSAEFONG\b'), 'OU SAEFONG'),
    (re.compile(r'(?i)\bTENSTRIKE\b'), 'TENSTRIKE LLC'),
    (re.compile(r'(?i)\bTRINITY\b'), 'TRINITY CONSULTING AND HOLDINGS'),
    (re.compile(r'(?i)\bTWENTY8GRAMZ\b'), 'TWENTY8GRAMZ'),
    (re.compile(r'(?i)\bWEBSTAURANT\b'), 'THE WEBSTAURANT STORE INC'),
    (re.compile(r'(?i)\bZIPPY\b'), 'KWIK SERV'),
    (re.compile(r'(?i)\bFOUR\b'), 'MT DIABLO'),
    (re.compile(r'(?i)\b00000WESTLEY\b'), 'GAWFCO WESTLEY'),
    (re.compile(r'(?i)\bVENMO\b'), 'VENMO'),
    (re.compile(r'(?i)\bMOVING\b'), 'U-HAUL'),
    (re.compile(r'(?i)\bFORMATION\b'), 'LEGALZOOM'),
    (re.compile(r'(?i)\bLZC\b'), 'LEGALZOOM'),
    (re.compile(r'(?i)\bNETWORKS\b'), 'SPAGHETTI NETWORK INC'),
    (re.compile(r'(?i)\bWINGSTOP\b'), 'DOORDASH'),
    (re.compile(r'(?i)\b07127ARCO\b'), 'ARCO'),
    (re.compile(r'(?i)\b83321BASRA\b'), 'ARCO'),
    (re.compile(r'(?i)\b83332WINTERS\b'), 'ARCO'),
    (re.compile(r'(?i)\bARCBUTTONWILLOW\b'), 'ARCO'),
    (re.compile(r'(?i)\bACDFEE\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bARMOREDCAR\b'), 'ARMORED CAR'),
    (re.compile(r'(?i)\bCHEVBERKELEY\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bCHEVORINDA\b'), 'CHEVRON'),
    (re.compile(r'(?i)\bBILLPAY\b'), 'ODOO B2B'),
    (re.compile(r'(?i)\bMEGANS\b'), 'ODOO B2B'),
    (re.compile(r'(?i)\bNICE\b'), 'ODOO B2B'),
    (re.compile(r'(?i)\bNORTHBAY\b'), 'ODOO B2B'),
    (re.compile(r'(?i)\bRETA\b'), 'AMAZON'),
    (re.compile(r'(?i)\b3QHK\b'), 'GUSTO'),
    (re.compile(r'(?i)\bBRIANA\b'), 'PAYNW'),
    (re.compile(r'(?i)\bJAVEN\b'), 'PAYNW'),
    (re.compile(r'(?i)\bJOHNSON\b'), 'PAYNW'),
    (re.compile(r'(?i)\bKANDY\b'), 'PAYNW'),
    (re.compile(r'(?i)\bMARIA\b'), 'PAYNW'),
    (re.compile(r'(?i)\bMORALES\b'), 'PAYNW'),
    (re.compile(r'(?i)\bYENI\b'), 'PAYNW'),
    (re.compile(r'(?i)\bCOMMERCE\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bSERIAL\b'), 'GUSTO'),
    (re.compile(r'(?i)\bLABS\b'), 'BELCOSTA LABS'),
    (re.compile(r'(?i)\bTWILIO\b'), 'TWILIO'),
    (re.compile(r'(?i)\bINVESTMENTS\b'), 'TUV INVESTMENTS'),
    (re.compile(r'(?i)\bEBMUD\b'), 'EBMUD'),
    (re.compile(r'(?i)\bOAK\b'), 'AEROPAY'),
    (re.compile(r'(?i)\bPRIVATE\b'), 'H & L PRIVATE SECURITY'),
    (re.compile(r'(?i)\bWEST\b'), 'WEST TOWN BNK'),
    (re.compile(r'(?i)\bAMEX\b'), 'CC'),
    (re.compile(r'(?i)\bMISC\b'), 'EASTWEST BANK'),
    (re.compile(r'(?i)\bDEPOS\b'), 'OSS'),
    (re.compile(r'(?i)\bXXXXXXXXXXXX8205\b'), 'AMAZON'),
    (re.compile(r'(?i)\bHUMANA\b'), 'HUMANA, INC.'),
    (re.compile(r'(?i)\bGPS\b'), 'PAYNW'),
    (re.compile(r'(?i)\bDCC\b'), 'DCC'),
    (re.compile(r'(?i)\bDINING\b'), 'DOORDASH'),
    (re.compile(r'(?i)\bGREEN\b'), 'LEDGER GREEN'),
    (re.compile(r'(?i)\bHONG\b'), 'ALIBABA'),
    (re.compile(r'(?i)\bMEDIA\b'), 'LB MEDIA GROUP LLC'),
    (re.compile(r'(?i)\bHARBOR\b'), 'HARBOR HR LLC'),
    (re.compile(r'(?i)\bLAB\b'), 'HARRENS LAB INC.'),
    (re.compile(r'(?i)\bEXXON\b'), 'EXXON'),
    (re.compile(r'(?i)\bDIXON\b'), 'DIXON GAS & SHOP'),
    (re.compile(r'(?i)\bACCOUNT\b'), 'GREENBAX MARKETPLACE'),
    (re.compile(r'(?i)\bCASH\b'), 'SWITCH COMMERCE'),
    (re.compile(r'(?i)\bREBILL\b'), 'E-Z*PASS'),
    (re.compile(r'(?i)\bLC2400\b'), 'LC 2400 (CLOVER VALLEY)'),
    (re.compile(r'(?i)\bLESS\b'), 'GAS 4 LESS'),
    (re.compile(r'(?i)\bDELIV\b'), 'COSTCO'),
    (re.compile(r'(?i)\bLOCAL\b'), 'WEINSTEIN LOCAL'),
    (re.compile(r'(?i)\b08\.01\.2023\b'), 'PAYNW'),
    (re.compile(r'(?i)\bDEEP\b'), 'DEEP ROOTS'),
    (re.compile(r'(?i)\bINN\b'), 'HOLIDAY INN'),
    (re.compile(r'(?i)\bLONG\b'), 'BELCOSTA LABS'),
    (re.compile(r'(?i)\bSOFTWARE\b'), 'KLAVIYO'),
    (re.compile(r'(?i)\bDOORDASH\b'), 'DOORDASH'),
    (re.compile(r'(?i)\bTELECHK\b'), 'KAISER'),
    (re.compile(r'(?i)\bCOLLECTIVE\b'), 'SCZZ COLLECTIVE'),
    (re.compile(r'(?i)\bPSADMINIST\b'), 'PS ADMINISTRATORS'),
    (re.compile(r'(?i)\bCOMP\b'), 'STATE COMP'),
    (re.compile(r'(?i)\bINTEREST\b'), 'HUMAN INTEREST'),
    (re.compile(r'(?i)\bMASH\b'), 'MASH GAS'),
    (re.compile(r'(?i)\bPACAFI\b'), 'PCF DISTRO'),
    (re.compile(r'(?i)\bPCF\b'), 'PCF DISTRO'),
    (re.compile(r'(?i)\bSMO\b'), 'PAYNW'),
    (re.compile(r'(?i)\bSUPPLIES\b'), 'ULINE'),
    (re.compile(r'(?i)\bWORLD\b'), 'WORLDWIDE ATM'),
    (re.compile(r'(?i)\bINVO\b'), 'H & L PRIVATE SECURITY'),
    (re.compile(r'(?i)\bUNITED\b'), 'UNITED'),
    (re.compile(r'(?i)\bTRUST\b'), 'MATRIX TRUST'),
    (re.compile(r'(?i)\bGSUITE_SMOAKLA\b'), 'GOOGLE GSUITE'),
    (re.compile(r'(?i)\bINDUS\b'), 'HAPPY PORT'),
    (re.compile(r'(?i)\bROTTEN\b'), 'ROTTEN ROBBIE'),
    (re.compile(r'(?i)\bSETTLEMENT\b'), 'STRONGHOLD'),
    (re.compile(r'(?i)\bSQUARE\b'), 'MORGAN AT PROVOST SQUARE'),
    (re.compile(r'(?i)\bFAMILY\b'), 'FAMILY FLORALS'),
    (re.compile(r'(?i)\bOIL\b'), 'SHELL'),
    (re.compile(r'(?i)\b08\.14\.2023\b'), 'PAYNW'),
    (re.compile(r'(?i)\bANTIOCH\b'), 'ANTIOCH LLC'),
    (re.compile(r'(?i)\bAREA\b'), 'AREA 29 LLC'),
    (re.compile(r'(?i)\bFHL\b'), 'FHL WEB INC'),
]

# --- Helpers -----------------------------------------------------------------

_SOURCE_COLS = [
    "bank_account", "subentity", "bank_cc_num",
    "description", "extended_description",
]

_RULEBOOK_NAME = "payee_vendor"
_RULEBOOK_VERSION = "2025.10.03"

def _normalize_text(s: str) -> str:
    """Normalize string casing and spacing for consistent regex matching."""
    if not isinstance(s, str):
        return ""
    s = s.upper().strip()
    return " ".join(s.split())

def _concat_row(row: dict) -> str:
    """Concatenate the key source columns into one normalized text string."""
    parts = [str(row.get(c, "") or "") for c in _SOURCE_COLS]
    return _normalize_text(" | ".join([p for p in parts if p]))

def build_search_text(df: pd.DataFrame) -> pd.Series:
    """
    Build a full-text search string per row by concatenating key columns.
    Used in vectorized rule application.
    """
    parts = []
    for c in _SOURCE_COLS:
        if c in df.columns:
            parts.append(df[c].fillna("").astype(str))
        else:
            parts.append(pd.Series([""] * len(df)))
    text = pd.Series([""] * len(df))
    for p in parts:
        text = text.str.cat(p, sep=" | ")
    return text.map(_normalize_text)

def infer(row: dict) -> tuple[str, str]:
    """
    Row-level API for the categorization pipeline.

    Returns:
        tuple:
            - inferred_value (str): Payee/Vendor value or 'UNKNOWN'
            - rule_tag (str): Identifier of the matching rule in format
              '<rulebook>@<version>#<rule_id>'
    """
    text = _concat_row(row)
    for idx, (pat, payee) in enumerate(_RULES, start=1):
        # Supports both compiled regex and plain string patterns
        if pat.search(text) if hasattr(pat, "search") else re.search(pat, text):
            return payee, f"{_RULEBOOK_NAME}@{_RULEBOOK_VERSION}#{idx}"
    return "UNKNOWN", ""

def apply_rules(df: pd.DataFrame) -> pd.DataFrame:
    """
    Vectorized API — useful for QA and batch validation.

    Adds the following columns:
        - payee_vendor (str)
        - payee_rule_id (Int64)
        - payee_rule_tag (str)
        - payee_confidence (float) = 1.0 if matched, 0.0 otherwise
        - payee_source (str) = 'rule' if matched, 'unknown' otherwise

    Rows with no match are explicitly labeled as 'UNKNOWN'.
    """
    out = df.copy()
    search = build_search_text(out)

    out["payee_vendor"] = ""
    out["payee_rule_id"] = pd.Series([pd.NA] * len(out), dtype="Int64")
    out["payee_rule_tag"] = ""
    out["payee_confidence"] = 0.0
    out["payee_source"] = "unknown"

    unmatched = out["payee_vendor"] == ""
    for i, (pat, payee) in enumerate(_RULES, start=1):
        # .str.contains() accepts both string and compiled regex
        mask = unmatched & search.str.contains(pat)
        if not mask.any():
            continue
        out.loc[mask, "payee_vendor"] = payee
        out.loc[mask, "payee_rule_id"] = i
        out.loc[mask, "payee_rule_tag"] = f"{_RULEBOOK_NAME}@{_RULEBOOK_VERSION}#{i}"
        out.loc[mask, "payee_confidence"] = 1.0
        out.loc[mask, "payee_source"] = "rule"
        unmatched = out["payee_vendor"] == ""

    # Fallback for unmatched rows
    out.loc[out["payee_vendor"] == "", "payee_vendor"] = "UNKNOWN"
    return out